INSERT INTO `torgi_mbc` (`id`, `url`, `name`) VALUES
(1, "/catalog/krediti/kredytni_portfeli/", "АТ БАНК МЕРКУРІЙ"),
(2, "/catalog/krediti/ab_-ukoopspilka_/", "АБ УКООПСПІЛКА "),
(3, "/catalog/krediti/at_-bank_tavryka/", "АТ БАНК ТАВРИКА"),
(4, "/catalog/krediti/at_-brokb-znesbank/", "АТ БРОКБІЗНЕСБАНК"),
(5, "/catalog/krediti/at_-evrogazbank/", "АТ ЄВРОГАЗБАНК"),
(6, "/catalog/krediti/at_-imeksbank/", "АТ ІМЕКСБАНК"),
(7, "/catalog/krediti/at_-porto-franko/", "АТ ПОРТО-ФРАНКО"),
(8, "/catalog/krediti/at_-_bank_zoloti_vorota_-_/", "АТ « БАНК ЗОЛОТІ ВОРОТА » "),
(9, "/catalog/krediti/at_-delta_bank/", "АТ «ДЕЛЬТА БАНК»"),
(10, "/catalog/krediti/at-bank_veles/", "АТБАНК ВЕЛЕС"),
(11, "/catalog/krediti/pat_-akb_bank/", "ПАТ АКБ БАНК"),
(12, "/catalog/krediti/pat_-aktabank/", "ПАТ АКТАБАНК"),
(13, "/catalog/krediti/pat_-bank_-kyyivs%60ka_rus%60/", "ПАТ БАНК Київська Русь"),
(14, "/catalog/krediti/pat_-bank_aksioma/", "ПАТ БАНК АКСІОМА"),
(15, "/catalog/krediti/pat_-bank_demark/", "ПАТ БАНК ДЕМАРК"),
(16, "/catalog/krediti/pat_-bank_nats-onalniy_kredit/", "ПАТ БАНК НАЦІОНАЛЬНИЙ КРЕДИТ"),
(17, "/catalog/krediti/pat_-bank_forum/", "ПАТ БАНК ФОРУМ"),
(18, "/catalog/krediti/pat_-bg_bank/", "ПАТ БГ Банк"),
(19, "/catalog/krediti/pat_-vieybi_bank/", "ПАТ ВіЕйБі БАНК"),
(20, "/catalog/krediti/pat_-energobank/", "ПАТ ЕНЕРГОБАНК"),
(21, "/catalog/krediti/pat_-zakh-d-nkombank/", "ПАТ ЗАХІДІНКОМБАНК"),
(22, "/catalog/krediti/pat_-zlatobank/", "ПАТ ЗЛАТОБАНК"),
(23, "/catalog/krediti/pat_-kb_-aktiv-bank/", "ПАТ КБ АКТИВ-БАНК"),
(24, "/catalog/krediti/pat_-kb_-nadra/", "ПАТ КБ НАДРА"),
(25, "/catalog/krediti/pat_-kb_dan-el/", "ПАТ КБ ДАНІЕЛЬ"),
(26, "/catalog/krediti/pat_-kreditprombank/", "ПАТ КРЕДИТПРОМБАНК"),
(27, "/catalog/krediti/pat_-legbank/", "ПАТ ЛЕГБАНК"),
(28, "/catalog/krediti/pat_-miskyy_komertsiynyy_bank_/", "ПАТ МІСЬКИЙ КОМЕРЦІЙНИЙ БАНК "),
(29, "/catalog/krediti/pat_-radikal_bank/", "ПАТ РАДИКАЛ БАНК"),
(30, "/catalog/krediti/pat_-staroki-vskiy_bank/", "ПАТ СТАРОКИЇВСЬКИЙ БАНК"),
(31, "/catalog/krediti/pat_-ukrbiznesbank/", "ПАТ УКРБІЗНЕСБАНК"),
(32, "/catalog/krediti/pat_-ukrgazprombank/", "ПАТ УКРГАЗПРОМБАНК"),
(33, "/catalog/krediti/pat_-upb/", "ПАТ УПБ"),
(34, "/catalog/krediti/pat_-_grin_bank_/", "ПАТ « Грін Банк »"),
(35, "/catalog/krediti/pat_-_integral-bank_-_/", "ПАТ « ІНТЕГРАЛ-БАНК » "),
(36, "/catalog/krediti/pat_-akb_-kapital/", "ПАТ «АКБ «КАПІТАЛ»"),
(37, "/catalog/krediti/pat_-akb_-kyyiv-_/", "ПАТ «АКБ «КИЇВ» "),
(38, "/catalog/krediti/pat_-interkredytbank_/", "ПАТ «ІНТЕРКРЕДИТБАНК »"),
(39, "/catalog/krediti/pat_-kb_ufs/", "ПАТ «КБ УФС»"),
(40, "/catalog/krediti/pat_-praym-bank/", "ПАТ «ПРАЙМ-БАНК»"),
(41, "/catalog/krediti/pat_-prof-n_bank/", "ПАТ «ПРОФІН БАНК»"),
(42, "/catalog/krediti/pat_-terra_bank/", "ПАТ «ТЕРРА БАНК»"),
(43, "/catalog/krediti/pat_ab_-stolychnyy/", "ПАТ АБ СТОЛИЧНИЙ"),
(44, "/catalog/krediti/pat_bank_-kontrakt/", "ПАТ БАНК КОНТРАКТ"),
(45, "/catalog/krediti/pat_bank_-melior/", "ПАТ БАНК МЕЛІОР"),
(46, "/catalog/krediti/pat_kb_-pivdenkombank/", "ПАТ КБ ПІВДЕНКОМБАНК"),
(47, "/catalog/krediti/pat_kb_-_interbank_/", "ПАТ КБ « ІНТЕРБАНК »"),
(48, "/catalog/krediti/pat_kb_promekonombank/", "ПАТ КБ ПРОМЕКОНОМБАНК");